import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import AdminSidebar from "@/components/admin/AdminSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function AdminLayout({ children }) {
  return (
    <div className="flex min-h-screen bg-primary">
      <AdminSidebar />
      <main className="ml-64 flex-1 p-4">
        {children}
      </main>
    </div>
  );
}
